name: Update Tax Config using the latest data from ATO

on:
  schedule:
    # Runs at midnight on Jan 1 and Jul 1 every year (every 6 months)
    - cron: "0 0 1 1,7 *"
  workflow_dispatch: # also allow manual trigger

jobs:
  update-tax-config:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Check Bun
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Run setup script
        run: bun run setup:tax-config

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b chore/update-tax-config-$(date +%Y%m%d%H%M%S)
          git add .
          git commit -m "chore: update tax config with latest changes" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/update-tax-config-$(date +%Y%m%d%H%M%S)
          base: main
          title: "chore: update tax config"
          body: "Automated update of tax configuration (runs every 6 months)."
          commit-message: "chore: update tax config with latest changes"
